name: Compile Latex and Release PDF  

on:
  push:
    tags:
      - '*.*.*'
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install additionnal packages
        run: |
          sudo apt-get update \
          && sudo apt-get -y install --no-install-recommends apt-utils 2>&1
          sudo apt-get update && sudo apt-get -y upgrade \
          && sudo apt-get -y install --no-install-recommends \
          texlive-latex-base \
          texlive-extra-utils \
          texlive-latex-extra \
          texlive-bibtex-extra \
          biber chktex latexmk make python3-pygments python3-pkg-resources \
          texlive-lang-french
          sudo apt-get install --no-install-recommends -y curl
          sudo curl -L http://cpanmin.us | perl - App::cpanminus \
          && cpanm Log::Dispatch::File && cpanm YAML::Tiny && cpanm File::HomeDir \
          && cpanm Unicode::GCString
          sudo apt-get autoremove -y && sudo apt-get clean -y && sudo rm -rf /var/lib/apt/lists/*
          
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            pdflatex -synctex=1 -interaction=nonstopmode -file-line-error Project.tex
            makeglossaries Project
            pdflatex -synctex=1 -interaction=nonstopmode -file-line-error Project.tex
            pdflatex -synctex=1 -interaction=nonstopmode -file-line-error Project.tex

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions PDF generated
          to: ${{secrets.MAIL_USERNAME}}@gmail.com
          from: ${{secrets.MAIL_USERNAME}} 
          secure: true
          body: PDF generated !
          attachments: ./Project.pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./Project.pdf
          asset_name: Project.pdf
          asset_content_type: pdf